### PR TITLE
Upgrade to Scala 3.0.0-RC1

### PR DESCRIPTION
**Pull request by jodersky**
pending https://github.com/lihaoyi/utest/pull/232 and https://github.com/lihaoyi/sourcecode/pull/103

### CODE REVIEW

**Comment by nightscape** [comment]
Hi @jodersky, both utest and sourcecode have been published for 3.0.0-RC1.
I think you only have to make some change to the code to trigger a new build.

**Comment by anatoliykmetyuk** [comment]
CI restarted, build green: https://travis-ci.org/github/lihaoyi/fansi/builds/759469017
Didn't update the check mark for some reason.

**Comment by nightscape** [comment]
@anatoliykmetyuk nice!
Would it be possible to release a version for 3.0.0-RC1 so that the @alexarchambault Ammonite build can be updated as well?

**Comment by anatoliykmetyuk** [comment]
Already on Maven🙂

**Pull request merged**
